name: Flutter Web
on:
  push:
    branches:
      -master
     
jobs:
  build:
    name: Build Web and Deploy
    runs-on: ubuntu-lastest
    env:
      BASE_HREF: /${{ github.event.repository.name }}/
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          channel: 'stable'
      - run: flutter build web --release --base-href $BASE_HREF
      - name: Deply gh-pages 
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
    
