name: Gh-Pages
on:
  push:
    branches: [ master]
      
     
jobs:
  build:
    runs-on: ubuntu-lastest
    
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
       
    
