name: Flutter Web
on:
  push:
    branches:
      -main
      

jobs:
  build:
    name: Build Web and Deploy
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'any'
      - run: flutter --version
    
